### ISSUE TITLE
Feature Request: Lock Commands / Command Groups based on Roles

### ISSUE THREAD

**Issue by evidex** [AdityaTD/PenguBot#22]
Lock a command or set of commands to particular roles.

This would allow users with the specified roles to execute the command, whilst denying those without the role.

Potentially, this could be achieved by locking command execution to particular channels, rather than roles, such that any users in a specified channel may execute the command, but not in other channels.

**Comment by AdityaTD** [comment]
This does sound like a good idea and I definitely think we should do this, I, unfortunately, can't tell you the ETA for when it'd be done but this because almost all contributors are currently busy with core functionality but we'll definitely work on this sooner or later. Thanks for the suggestion.
