### ISSUE TITLE
Redo this command

### ISSUE THREAD

**Issue by Kashalls** [AdityaTD/PenguBot#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

----------------------------------------------------------------------------------------

https://github.com/AdityaTD/PenguBot/blob/rewrite/commands/Music/play.js

Redo this command, I see a bunch of wasted timing. If I was Kyra, you would be dead.

**Comment by AdityaTD** [comment]
Check the branch Quantum-full-voice, Quantum is rewriting music currently.

**Comment by MrJacz** [comment]
We're currently rewriting music
