### ISSUE TITLE
Check this

### ISSUE THREAD

**Issue by Kashalls** [AdityaTD/PenguBot#27]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

------------------------------------
I recommend using const for anything you dont reassign.

https://github.com/AdityaTD/PenguBot/blob/rewrite/finalizers/commandCounter.js

**Comment by AdityaTD** [comment]
I am reassigning values in the `if` statement if you see, I can't do it if I use `const` because otherwise, the counter would have invalid entries. I've tried other ways of doing it but this one worked out perfectly fine.
