### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [AdityaTD/PenguBot#33]
Greetings @AdityaTD  ,

I was passing by (this repository) and tought I'd like to collaborate by proposing a logo
if that's something that may interest you! let me know!

I'm a Graphic Designer and an Open Source enthusiastic
looking to improve my portfolio and collaborate to really cool projects like this one!

Best Regards,
-Luigi.

**Comment by IceeMC** [comment]
uwot

**Comment by QuantumlyTangled** [comment]
Ice please formulate complete sentances and not meme like ones.

**Comment by AdityaTD** [comment]
Hey sure, if you can show us some of your work I'd be more than interested as I am a graphics designer and developer myself :)

Thanks for showing interest in our project!

**Comment by AdityaTD** [comment]
Oh and also, feel free to DM me on Discord `AdityaTD#5346` and or join our community guild: https://www.pengubot.com/support

**Comment by LuigiBaute** [comment]
This isn't my actual portfolio, this are some of the .png I had made before for some repos, for you to take a look at google drive the repo's I have worked with are visible on my profile +1 @AdityaTD 
https://drive.google.com/drive/folders/1DBM4sp91l8CDZsOm16o0ZrczawsmwoDU?usp=sharing

**Comment by AdityaTD** [comment]
They look good but our theme is Penguin and color Blue, can you maybe make a rough draft to show how it'll look if finalized and also I hope you're making these in Illustrator so they can be scaled. I can't promise if I'd use it or not but if it's good I don't see why not 👍 Thanks

**Comment by LuigiBaute** [comment]
Sure @AdityaTD ,
no problem I upload it in a .pdf format which is perfectly scalable,
I'll upload my proposal when ready, and of course you decide if use it or not, that's not a problem for me.

cheers.

**Comment by AdityaTD** [comment]
@LuigiBaute Any updates? If you can't do it, it's fine, let us know 👍

**Comment by AdityaTD** [comment]
No Response, Closing.
