### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by Tqcoz** [AdityaTD/PenguBot#65]
**Is your feature request related to a problem? Please describe.**
No My Feature is not a problem

**Describe the solution you'd like**
A Discord Bot Dashboard using JSON as a Database instead of enmap and sql

**Describe alternatives you've considered**
I am not really sure what other alternatives there is except for the one I already listed: enmap but it is quite hard to set that up and get it working.

**Additional context**
https://mee6.xyz, https://dynobot.net, etc

**Comment by AdityaTD** [comment]
This is already in the works and a lot of progress has already been made on this.

**Comment by MrJacz** [comment]
this doesn't use Enmap or Sql?
please elaborate on why you said that

**Comment by AdityaTD** [comment]
I think they meant that we should use some sort of a database so that we could make an API for it and use with a web dashboard so users can use it...

**Comment by ionadev** [comment]
Pengu Uses Rethink DB iirc.
